# Generated by Django 4.1.1 on 2022-09-09 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itempage',
            name='subject',
            field=models.CharField(max_length=250),
        ),
    ]
