# Generated by Django 4.1.1 on 2022-09-09 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_moviepagetag_moviepage_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviepage',
            name='rating',
            field=models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9)], null=True),
        ),
    ]
