# Generated by Django 4.1.1 on 2022-09-09 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_moviepage_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviepage',
            name='subject',
            field=models.CharField(default='Movie', max_length=250),
        ),
        migrations.AlterField(
            model_name='moviepage',
            name='rating',
            field=models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], null=True),
        ),
    ]
